services:
  training:
    build: backend
    command: python model.py
    environment:
      PYTHONUNBUFFERED: 0
    volumes:
      - models:/checkpoints
    deploy:
      resources:
        reservations:
          memory: 16Gb
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  translator:
    build: backend
    volumes:
      - models:/checkpoints

  frontend:
    build: frontend
    ports:
      - 80:80
    depends_on:
      - translator

volumes:
  models:
